In [1]:
import pandas as pd
import numpy as np

In [12]:
movies = pd.read_excel(r"C:\Users\abhis\OneDrive\Desktop\tmdb_5000_movies.csv.xlsx")
credits = pd.read_excel(r"C:\Users\abhis\OneDrive\Desktop\tmdb_5000_credits.csv.xlsx")

In [13]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [14]:
credits.head(1)

,movie_id,title,cast,crew,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 1255,Unnamed: 1256,Unnamed: 1257,Unnamed: 1258,Unnamed: 1259,Unnamed: 1260,Unnamed: 1261,Unnamed: 1262,Unnamed: 1263,Unnamed: 1264
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
movies.merge(credits,on = 'title').shape

(4809, 1284)

In [16]:
movies = movies.merge(credits,on = 'title')

In [17]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,Unnamed: 1255,Unnamed: 1256,Unnamed: 1257,Unnamed: 1258,Unnamed: 1259,Unnamed: 1260,Unnamed: 1261,Unnamed: 1262,Unnamed: 1263,Unnamed: 1264
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# genres
# id
# keywords
# title
# overview
# cast
# crew

In [19]:
movies['original_language'].value_counts()

original_language
en    4520
fr      70
es      32
zh      27
de      27
hi      19
ja      16
ko      14
it      14
cn      12
ru      11
pt       9
da       7
sv       5
nl       4
fa       4
th       3
he       3
id       2
cs       2
ta       2
ro       2
ar       2
te       1
hu       1
xx       1
af       1
is       1
tr       1
vi       1
pl       1
nb       1
ky       1
no       1
sl       1
ps       1
el       1
Name: count, dtype: int64

In [20]:
movies = movies.merge(credits,on = 'title')
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [21]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4845 entries, 0 to 4844
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4845 non-null   object
 1   title     4845 non-null   object
 2   overview  4842 non-null   object
 3   genres    4845 non-null   object
 4   keywords  4845 non-null   object
 5   cast      4845 non-null   object
 6   crew      4841 non-null   object
dtypes: object(7)
memory usage: 265.1+ KB

In [22]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [23]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        4
dtype: int64

In [24]:
movies.dropna(inplace = True)

In [25]:
movies.duplicated().sum()

np.int64(36)

In [28]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [27]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [29]:
def convert(obj):
  L = []
  for i in obj:
    L.append(i['name'])
  return L

In [30]:
def convert(obj):
  L = []
  for i in ast.literal_eval(obj):
    L.append(i['name'])
  return L

In [31]:
movies['genres'] = movies['genres'].apply(convert)

In [32]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [33]:
movies['keywords'] = movies['keywords'].apply(convert)

In [34]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [35]:
movies['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [36]:
def convert3(obj):
  L = []
  counter = 0
  for i in ast.literal_eval(obj):
    if counter != 3:
      L.append(i['name'])
      counter+=1
    else:
      break
  return L

In [37]:
movies['cast'].apply(convert3)

0        [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1           [Johnny Depp, Orlando Bloom, Keira Knightley]
2            [Daniel Craig, Christoph Waltz, Léa Seydoux]
3            [Christian Bale, Michael Caine, Gary Oldman]
4          [Taylor Kitsch, Lynn Collins, Samantha Morton]
                              ...
4840    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4841         [Edward Burns, Kerry Bishé, Marsha Dietlein]
4842           [Eric Mabius, Kristin Booth, Crystal Lowe]
4843            [Daniel Henney, Eliza Coupe, Bill Paxton]
4844    [Drew Barrymore, Brian Herzlinger, Corey Feldman]
Name: cast, Length: 4838, dtype: object

In [38]:
movies['cast'] = movies['cast'].apply(convert3)

In [39]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [40]:
movies['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [41]:
def fetch_director(obj):
  L = []
  for i in ast.literal_eval(obj):
    if i['job'] == 'Director':
      L.append(i['name'])
      break
  return L

In [42]:
import ast

def fetch_director(obj):
  L = []
  try:
    list_of_dicts = ast.literal_eval(obj)
    for i in list_of_dicts:
      if i['job'] == 'Director':
        L.append(i['name'])
        break
  except (ValueError, SyntaxError):
    # Handle cases where the string is malformed or truncated
    return []
  return L

movies['crew'] = movies['crew'].apply(fetch_director)

In [43]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [44]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [45]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [46]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, se...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [47]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
# movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [48]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, se...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[Christian Bale, Michael Caine, Gary Oldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[AndrewStanton]

In [49]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [50]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, se...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, se..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[Christian Bale, Michael Caine, Gary Oldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [51]:
new_df = movies[['movie_id','title','tags']]

In [52]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, se..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4840,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4841,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4842,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4843,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4844,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [53]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\abhis\AppData\Local\Temp\ipykernel_23496\3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [54]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [55]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d Sam Worthington Zoe Saldana Sigourney Weaver JamesCameron'

In [56]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\abhis\AppData\Local\Temp\ipykernel_23496\3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [57]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [59]:
!pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Collecting nltk
  Downloading nltk-3.9.3-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: click in c:\users\abhis\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in c:\users\abhis\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from nltk) (1.5.3)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2026.2.28-cp312-cp312-win_amd64.whl.metadata (41 kB)
Collecting tqdm (from nltk)
  Using cached tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: colorama in c:\users\abhis\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.9.3-py3-none-any.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.5 MB ? eta -:--:--
   -------------------- ------------------- 0.8/1.5 MB 2.4 MB/s eta 0:00:01
   ---------------------------------- ----- 1.3/1.5 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 2.4 MB/s eta 0:00:00
Downloading regex-2026.2.28-cp312-cp312-win_amd64.whl (277 kB)
Using cached tqdm-4.67.3-py3-none-any.whl (78 kB)
Installing collected packages: tqdm, regex, nltk
Successfully installed nltk-3.9.3 regex-2026.2.28 tqdm-4.67.3

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: C:\Users\abhis\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [60]:
import nltk

In [61]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [62]:
def stem(text):
  y = []

  for i in text.split():
    y.append(ps.stem(i))

  return " ".join(y)

In [63]:
new_df['tags'].apply(stem)

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bondâ€™ past send him on...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...
4840    el mariachi just want to play hi guitar and ca...
4841    a newlyw couple' honeymoon is upend by the arr...
4842    "signed, sealed, delivered" introduc a dedic q...
4843    when ambiti new york attorney sam is sent to s...
4844    ever sinc the second grade when he first saw h...
Name: tags, Length: 4838, dtype: object

In [64]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d sam worthington zoe saldana sigourney weaver jamescameron'

In [65]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [66]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [67]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(5000,))

In [68]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooey'],
      shape=(5000,), dtype=object)

In [69]:
['loved','love','loving']
['love','love','love']

['love', 'love', 'love']

In [70]:
ps.stem('danced')

'danc'

In [75]:
stem('in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d sam worthington zoe saldana sigourney weaver jamescameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d sam worthington zoe saldana sigourney weaver jamescameron'

In [72]:
from sklearn.metrics.pairwise import cosine_similarity

In [73]:
similarity = cosine_similarity(vectors)

In [74]:
similarity[1]

array([0.08346223, 1.        , 0.06262243, ..., 0.02501564, 0.        ,
       0.        ], shape=(4838,))

In [76]:
list(enumerate(similarity[0]))

[(0, np.float64(1.0000000000000002)),
 (1, np.float64(0.08346223261119858)),
 (2, np.float64(0.05923488777590923)),
 (3, np.float64(0.03771571432023571)),
 (4, np.float64(0.1692777916923361)),
 (5, np.float64(0.11357771260606365)),
 (6, np.float64(0.021300716142115247)),
 (7, np.float64(0.16563698349810535)),
 (8, np.float64(0.0582716546748065)),
 (9, np.float64(0.07254762501100118)),
 (10, np.float64(0.10814761408717502)),
 (11, np.float64(0.07792865001991967)),
 (12, np.float64(0.09037128496931669)),
 (13, np.float64(0.046348977465932154)),
 (14, np.float64(0.10814761408717502)),
 (15, np.float64(0.047324852428030105)),
 (16, np.float64(0.07509392614826384)),
 (17, np.float64(0.14084763640246842)),
 (18, np.float64(0.09558988911273408)),
 (19, np.float64(0.08447772061910234)),
 (20, np.float64(0.05510387687779837)),
 (21, np.float64(0.08346223261119858)),
 (22, np.float64(0.06362847629757779)),
 (23, np.float64(0.08603090020146065)),
 (24, np.float64(0.052631578947368425)),
 (25, np.float64(0.03604920469572501)),
 (26, np.float64(0.15789473684210528)),
 (27, np.float64(0.1782626071286346)),
 (28, np.float64(0.11128297681493143)),
 (29, np.float64(0.06814662756363819)),
 (30, np.float64(0.06748819059987714)),
 (31, np.float64(0.15061880828219448)),
 (32, np.float64(0.08594700851870801)),
 (33, np.float64(0.09365858115816941)),
 (34, np.float64(0.0)),
 (35, np.float64(0.1324532357065044)),
 (36, np.float64(0.18183351671314588)),
 (37, np.float64(0.07792865001991967)),
 (38, np.float64(0.05816750507471109)),
 (39, np.float64(0.12824729401064427)),
 (40, np.float64(0.050669459193814)),
 (41, np.float64(0.13764944032233706)),
 (42, np.float64(0.0)),
 (43, np.float64(0.11357771260606365)),
 (44, np.float64(0.03539961627023944)),
 (45, np.float64(0.08594700851870801)),
 (46, np.float64(0.16222142113076252)),
 (47, np.float64(0.22305445405479846)),
 (48, np.float64(0.06622661785325219)),
 (49, np.float64(0.0582716546748065)),
 (50, np.float64(0.11470786693528087)),
 (51, np.float64(0.07868894753646337)),
 (52, np.float64(0.16222142113076252)),
 (53, np.float64(0.050669459193814)),
 (54, np.float64(0.03065696697424829)),
 (55, np.float64(0.07594632491572426)),
 (56, np.float64(0.12977713690461004)),
 (57, np.float64(0.028239124736245257)),
 (58, np.float64(0.043355498476206004)),
 (59, np.float64(0.07443229275647868)),
 (60, np.float64(0.026315789473684213)),
 (61, np.float64(0.20751433915982237)),
 (62, np.float64(0.07079923254047887)),
 (63, np.float64(0.08671099695241201)),
 (64, np.float64(0.028676966733820218)),
 (65, np.float64(0.019117977822546817)),
 (66, np.float64(0.023174488732966077)),
 (67, np.float64(0.16452254913212452)),
 (68, np.float64(0.12262786789699316)),
 (69, np.float64(0.04916051440083466)),
 (70, np.float64(0.08226127456606226)),
 (71, np.float64(0.07421560439929402)),
 (72, np.float64(0.11470786693528087)),
 (73, np.float64(0.03181423814878889)),
 (74, np.float64(0.21296183592613543)),
 (75, np.float64(0.08740748201220976)),
 (76, np.float64(0.07336739820667779)),
 (77, np.float64(0.014013796366780263)),
 (78, np.float64(0.05195243334661311)),
 (79, np.float64(0.07336739820667779)),
 (80, np.float64(0.03260773253630123)),
 (81, np.float64(0.11164843913471802)),
 (82, np.float64(0.076004188790721)),
 (83, np.float64(0.21073180760588117)),
 (84, np.float64(0.13476498501489084)),
 (85, np.float64(0.10092946653787335)),
 (86, np.float64(0.08471737420873576)),
 (87, np.float64(0.10814761408717502)),
 (88, np.float64(0.08346223261119858)),
 (89, np.float64(0.05874734954460467)),
 (90, np.float64(0.0602475233128778)),
 (91, np.float64(0.15061880828219448)),
 (92, np.float64(0.06622661785325219)),
 (93, np.float64(0.046829290579084706)),
 (94, np.float64(0.1777046633277277)),
 (95, np.float64(0.11831213107007527)),
 (96, np.float64(0.08346223261119858)),
 (97, np.float64(0.07254762501100118)),
 (98, np.float64(0.08346223261119858)),
 (99, np.float64(0.027036903521793755)),
 (100, np.float64(0.06765100914917384)),
 (101, np.float64(0.08111071056538127)),
 (102, np.float64(0.10559715077387793)),
 (103, np.float64(0.08240856434303293)),
 (104, np.float64(0.05484084971070818)),
 (105, np.float64(0.09544271444636668)),
 (106, np.float64(0.04188539082916955)),
 (107, np.float64(0.08671099695241201)),
 (108, np.float64(0.15311752374093252)),
 (109, np.float64(0.07443229275647868)),
 (110, np.float64(0.023414645289542353)),
 (111, np.float64(0.1976738731537168)),
 (112, np.float64(0.08603090020146065)),
 (113, np.float64(0.04947706959952935)),
 (114, np.float64(0.04891159880445185)),
 (115, np.float64(0.05195243334661311)),
 (116, np.float64(0.0533380747062665)),
 (117, np.float64(0.05564148840746572)),
 (118, np.float64(0.016643566632465155)),
 (119, np.float64(0.04543108504242546)),
 (120, np.float64(0.0)),
 (121, np.float64(0.08346223261119858)),
 (122, np.float64(0.08740748201220976)),
 (123, np.float64(0.11707322644771176)),
 (124, np.float64(0.06446025638903101)),
 (125, np.float64(0.07630253807827608)),
 (126, np.float64(0.106676149412533)),
 (127, np.float64(0.12940792666314374)),
 (128, np.float64(0.0)),
 (129, np.float64(0.0978231976089037)),
 (130, np.float64(0.02913582733740325)),
 (131, np.float64(0.12824729401064427)),
 (132, np.float64(0.06684847767323797)),
 (133, np.float64(0.0301237616564389)),
 (134, np.float64(0.12262786789699316)),
 (135, np.float64(0.0)),
 (136, np.float64(0.023918243661746996)),
 (137, np.float64(0.03382550457458692)),
 (138, np.float64(0.07792865001991967)),
 (139, np.float64(0.10060545457319173)),
 (140, np.float64(0.047324852428030105)),
 (141, np.float64(0.10147651372376076)),
 (142, np.float64(0.08226127456606226)),
 (143, np.float64(0.065033247714309)),
 (144, np.float64(0.05195243334661311)),
 (145, np.float64(0.021300716142115247)),
 (146, np.float64(0.016303866268150616)),
 (147, np.float64(0.057353933467640436)),
 (148, np.float64(0.09365858115816941)),
 (149, np.float64(0.16096872731710676)),
 (150, np.float64(0.19968076595771794)),
 (151, np.float64(0.1813690625275029)),
 (152, np.float64(0.0602475233128778)),
 (153, np.float64(0.08111071056538127)),
 (154, np.float64(0.0301237616564389)),
 (155, np.float64(0.0)),
 (156, np.float64(0.06335829046432676)),
 (157, np.float64(0.09933992677987831)),
 (158, np.float64(0.14509525002200235)),
 (159, np.float64(0.06131393394849658)),
 (160, np.float64(0.09183979479633063)),
 (161, np.float64(0.03539961627023944)),
 (162, np.float64(0.0331133089266261)),
 (163, np.float64(0.051298917604257706)),
 (164, np.float64(0.08740748201220976)),
 (165, np.float64(0.06952346619889824)),
 (166, np.float64(0.11470786693528087)),
 (167, np.float64(0.06243905410544627)),
 (168, np.float64(0.14843120879858804)),
 (169, np.float64(0.11037769642208699)),
 (170, np.float64(0.08594700851870801)),
 (171, np.float64(0.02782074420373286)),
 (172, np.float64(0.13530201829834768)),
 (173, np.float64(0.023662426214015053)),
 (174, np.float64(0.10259783520851541)),
 (175, np.float64(0.05006261743217589)),
 (176, np.float64(0.028676966733820218)),
 (177, np.float64(0.0)),
 (178, np.float64(0.023918243661746996)),
 (179, np.float64(0.06765100914917384)),
 (180, np.float64(0.02271554252121273)),
 (181, np.float64(0.02249606353329238)),
 (182, np.float64(0.101338918387628)),
 (183, np.float64(0.07038153430777869)),
 (184, np.float64(0.17521916101261562)),
 (185, np.float64(0.052631578947368425)),
 (186, np.float64(0.04087595596566438)),
 (187, np.float64(0.12988108336653278)),
 (188, np.float64(0.021677749238103002)),
 (189, np.float64(0.07079923254047887)),
 (190, np.float64(0.07755667343294813)),
 (191, np.float64(0.04783648732349399)),
 (192, np.float64(0.0)),
 (193, np.float64(0.08175191193132876)),
 (194, np.float64(0.0)),
 (195, np.float64(0.05564148840746572)),
 (196, np.float64(0.05484084971070818)),
 (197, np.float64(0.04588314677411236)),
 (198, np.float64(0.05484084971070818)),
 (199, np.float64(0.11037769642208699)),
 (200, np.float64(0.06917144638660747)),
 (201, np.float64(0.0)),
 (202, np.float64(0.031219527052723135)),
 (203, np.float64(0.08111071056538127)),
 (204, np.float64(0.023662426214015053)),
 (205, np.float64(0.07079923254047887)),
 (206, np.float64(0.13369695534647594)),
 (207, np.float64(0.07792865001991967)),
 (208, np.float64(0.15294382258037453)),
 (209, np.float64(0.03458572319330373)),
 (210, np.float64(0.050669459193814)),
 (211, np.float64(0.025334729596907)),
 (212, np.float64(0.07509392614826384)),
 (213, np.float64(0.061806423257274694)),
 (214, np.float64(0.028239124736245257)),
 (215, np.float64(0.06952346619889824)),
 (216, np.float64(0.06131393394849658)),
 (217, np.float64(0.042973504259354006)),
 (218, np.float64(0.0602475233128778)),
 (219, np.float64(0.1777046633277277)),
 (220, np.float64(0.02294157338705618)),
 (221, np.float64(0.0792740035289418)),
 (222, np.float64(0.07792865001991967)),
 (223, np.float64(0.05945550264670635)),
 (224, np.float64(0.04836508334066745)),
 (225, np.float64(0.02742042485535409)),
 (226, np.float64(0.08471737420873576)),
 (227, np.float64(0.12369267399882337)),
 (228, np.float64(0.07492686492653551)),
 (229, np.float64(0.08520286456846099)),
 (230, np.float64(0.0)),
 (231, np.float64(0.10968169942141635)),
 (232, np.float64(0.09933992677987831)),
 (233, np.float64(0.06446025638903101)),
 (234, np.float64(0.057353933467640436)),
 (235, np.float64(0.08740748201220976)),
 (236, np.float64(0.06488856845230502)),
 (237, np.float64(0.12166606584807191)),
 (238, np.float64(0.10385162309931599)),
 (239, np.float64(0.046348977465932154)),
 (240, np.float64(0.08346223261119858)),
 (241, np.float64(0.08603090020146065)),
 (242, np.float64(0.09269795493186431)),
 (243, np.float64(0.06243905410544627)),
 (244, np.float64(0.08471737420873576)),
 (245, np.float64(0.061806423257274694)),
 (246, np.float64(0.0)),
 (247, np.float64(0.04456565178215865)),
 (248, np.float64(0.1324532357065044)),
 (249, np.float64(0.0)),
 (250, np.float64(0.03721614637823934)),
 (251, np.float64(0.017914359097500464)),
 (252, np.float64(0.06684847767323797)),
 (253, np.float64(0.076004188790721)),
 (254, np.float64(0.0)),
 (255, np.float64(0.07868894753646337)),
 (256, np.float64(0.08111071056538127)),
 (257, np.float64(0.021119430154775586)),
 (258, np.float64(0.04836508334066745)),
 (259, np.float64(0.23693955110363693)),
 (260, np.float64(0.023918243661746996)),
 (261, np.float64(0.07098727864204515)),
 (262, np.float64(0.09733285267845754)),
 (263, np.float64(0.0)),
 (264, np.float64(0.02666903735313325)),
 (265, np.float64(0.10390486669322622)),
 (266, np.float64(0.0662266178532522)),
 (267, np.float64(0.025334729596907)),
 (268, np.float64(0.0301237616564389)),
 (269, np.float64(0.0967301666813349)),
 (270, np.float64(0.07509392614826384)),
 (271, np.float64(0.028676966733820218)),
 (272, np.float64(0.023414645289542353)),
 (273, np.float64(0.07664241743562072)),
 (274, np.float64(0.11470786693528087)),
 (275, np.float64(0.06362847629757779)),
 (276, np.float64(0.060833032924035954)),
 (277, np.float64(0.09567297464698798)),
 (278, np.float64(0.09464970485606021)),
 (279, np.float64(0.0)),
 (280, np.float64(0.06882472016116853)),
 (281, np.float64(0.02666903735313325)),
 (282, np.float64(0.0)),
 (283, np.float64(0.019252140716412975)),
 (284, np.float64(0.0207703246198632)),
 (285, np.float64(0.020277677641345318)),
 (286, np.float64(0.025334729596907)),
 (287, np.float64(0.0)),
 (288, np.float64(0.047324852428030105)),
 (289, np.float64(0.06362847629757779)),
 (290, np.float64(0.052631578947368425)),
 (291, np.float64(0.09197090092274487)),
 (292, np.float64(0.027036903521793755)),
 (293, np.float64(0.10968169942141635)),
 (294, np.float64(0.08998425413316952)),
 (295, np.float64(0.039344473768231684)),
 (296, np.float64(0.046829290579084706)),
 (297, np.float64(0.0)),
 (298, np.float64(0.03771571432023571)),
 (299, np.float64(0.17316974359835272)),
 (300, np.float64(0.16972071444106068)),
 (301, np.float64(0.05647824947249051)),
 (302, np.float64(0.027036903521793755)),
 (303, np.float64(0.06802170238514359)),
 (304, np.float64(0.17836650794011907)),
 (305, np.float64(0.08603090020146065)),
 (306, np.float64(0.09933992677987831)),
 (307, np.float64(0.06362847629757779)),
 (308, np.float64(0.0602475233128778)),
 (309, np.float64(0.03650267163704923)),
 (310, np.float64(0.14509525002200235)),
 (311, np.float64(0.10526315789473685)),
 (312, np.float64(0.07443229275647868)),
 (313, np.float64(0.0)),
 (314, np.float64(0.08346223261119858)),
 (315, np.float64(0.0)),
 (316, np.float64(0.0)),
 (317, np.float64(0.0)),
 (318, np.float64(0.0662266178532522)),
 (319, np.float64(0.03382550457458692)),
 (320, np.float64(0.0)),
 (321, np.float64(0.20780973338645242)),
 (322, np.float64(0.029617443887954616)),
 (323, np.float64(0.025334729596907)),
 (324, np.float64(0.09733285267845754)),
 (325, np.float64(0.05484084971070818)),
 (326, np.float64(0.027036903521793755)),
 (327, np.float64(0.0)),
 (328, np.float64(0.10390486669322622)),
 (329, np.float64(0.13334518676566626)),
 (330, np.float64(0.04588314677411236)),
 (331, np.float64(0.13518451760896877)),
 (332, np.float64(0.028676966733820218)),
 (333, np.float64(0.12369267399882336)),
 (334, np.float64(0.0533380747062665)),
 (335, np.float64(0.06362847629757779)),
 (336, np.float64(0.02249606353329238)),
 (337, np.float64(0.0)),
 (338, np.float64(0.052631578947368425)),
 (339, np.float64(0.04836508334066745)),
 (340, np.float64(0.057353933467640436)),
 (341, np.float64(0.13112201362143716)),
 (342, np.float64(0.021300716142115247)),
 (343, np.float64(0.028676966733820218)),
 (344, np.float64(0.021873931962990357)),
 (345, np.float64(0.0)),
 (346, np.float64(0.0)),
 (347, np.float64(0.05923488777590923)),
 (348, np.float64(0.08885233166386385)),
 (349, np.float64(0.050669459193814)),
 (350, np.float64(0.0)),
 (351, np.float64(0.02782074420373286)),
 (352, np.float64(0.02271554252121273)),
 (353, np.float64(0.0)),
 (354, np.float64(0.03823595564509363)),
 (355, np.float64(0.08226127456606226)),
 (356, np.float64(0.0)),
 (357, np.float64(0.05923488777590923)),
 (358, np.float64(0.031219527052723135)),
 (359, np.float64(0.0)),
 (360, np.float64(0.052631578947368425)),
 (361, np.float64(0.08885233166386385)),
 (362, np.float64(0.108388746190515)),
 (363, np.float64(0.023414645289542353)),
 (364, np.float64(0.07098727864204515)),
 (365, np.float64(0.052631578947368425)),
 (366, np.float64(0.0)),
 (367, np.float64(0.1324532357065044)),
 (368, np.float64(0.08111071056538127)),
 (369, np.float64(0.052631578947368425)),
 (370, np.float64(0.0967301666813349)),
 (371, np.float64(0.04891159880445185)),
 (372, np.float64(0.16222142113076254)),
 (373, np.float64(0.0415406492397264)),
 (374, np.float64(0.061806423257274694)),
 (375, np.float64(0.04588314677411236)),
 (376, np.float64(0.0)),
 (377, np.float64(0.0)),
 (378, np.float64(0.049930699897395465)),
 (379, np.float64(0.026315789473684213)),
 (380, np.float64(0.07443229275647868)),
 (381, np.float64(0.0)),
 (382, np.float64(0.050669459193814)),
 (383, np.float64(0.029617443887954616)),
 (384, np.float64(0.0)),
 (385, np.float64(0.02271554252121273)),
 (386, np.float64(0.025334729596907)),
 (387, np.float64(0.0)),
 (388, np.float64(0.09197090092274487)),
 (389, np.float64(0.026315789473684213)),
 (390, np.float64(0.058587492514838024)),
 (391, np.float64(0.028676966733820218)),
 (392, np.float64(0.0)),
 (393, np.float64(0.024182541670333724)),
 (394, np.float64(0.04456565178215865)),
 (395, np.float64(0.022282825891079324)),
 (396, np.float64(0.05195243334661311)),
 (397, np.float64(0.0)),
 (398, np.float64(0.023918243661746996)),
 (399, np.float64(0.09544271444636668)),
 (400, np.float64(0.029617443887954616)),
 (401, np.float64(0.05006261743217589)),
 (402, np.float64(0.10218988991416095)),
 (403, np.float64(0.0602475233128778)),
 (404, np.float64(0.02782074420373286)),
 (405, np.float64(0.021300716142115247)),
 (406, np.float64(0.024455799402225926)),
 (407, np.float64(0.03382550457458692)),
 (408, np.float64(0.0)),
 (409, np.float64(0.09365858115816941)),
 (410, np.float64(0.0533380747062665)),
 (411, np.float64(0.0967301666813349)),
 (412, np.float64(0.12515654358043973)),
 (413, np.float64(0.02913582733740325)),
 (414, np.float64(0.06765100914917384)),
 (415, np.float64(0.05195243334661311)),
 (416, np.float64(0.06488856845230502)),
 (417, np.float64(0.03382550457458692)),
 (418, np.float64(0.07509392614826384)),
 (419, np.float64(0.11959121830873498)),
 (420, np.float64(0.0)),
 (421, np.float64(0.13530201829834768)),
 (422, np.float64(0.047324852428030105)),
 (423, np.float64(0.039344473768231684)),
 (424, np.float64(0.06684847767323797)),
 (425, np.float64(0.05695974368679319)),
 (426, np.float64(0.028676966733820218)),
 (427, np.float64(0.05619514869490164)),
 (428, np.float64(0.0)),
 (429, np.float64(0.04947706959952935)),
 (430, np.float64(0.024182541670333724)),
 (431, np.float64(0.12227899701112964)),
 (432, np.float64(0.0301237616564389)),
 (433, np.float64(0.0)),
 (434, np.float64(0.03458572319330373)),
 (435, np.float64(0.0)),
 (436, np.float64(0.027036903521793755)),
 (437, np.float64(0.026315789473684213)),
 (438, np.float64(0.028239124736245257)),
 (439, np.float64(0.025031308716087945)),
 (440, np.float64(0.02782074420373286)),
 (441, np.float64(0.04543108504242546)),
 (442, np.float64(0.0533380747062665)),
 (443, np.float64(0.0)),
 (444, np.float64(0.026315789473684213)),
 (445, np.float64(0.023414645289542353)),
 (446, np.float64(0.022282825891079324)),
 (447, np.float64(0.024182541670333724)),
 (448, np.float64(0.05407380704358751)),
 (449, np.float64(0.024455799402225926)),
 (450, np.float64(0.025031308716087945)),
 (451, np.float64(0.026315789473684213)),
 (452, np.float64(0.024738534799764674)),
 (453, np.float64(0.11707322644771176)),
 (454, np.float64(0.023918243661746996)),
 (455, np.float64(0.06622661785325219)),
 (456, np.float64(0.08000711205939975)),
 (457, np.float64(0.044151078568834795)),
 (458, np.float64(0.03244428422615251)),
 (459, np.float64(0.026315789473684213)),
 (460, np.float64(0.17292861596651865)),
 (461, np.float64(0.0)),
 (462, np.float64(0.029617443887954616)),
 (463, np.float64(0.0)),
 (464, np.float64(0.0)),
 (465, np.float64(0.19088542889273336)),
 (466, np.float64(0.0891313035643173)),
 (467, np.float64(0.027036903521793755)),
 (468, np.float64(0.06562179588897107)),
 (469, np.float64(0.04588314677411236)),
 (470, np.float64(0.07509392614826384)),
 (471, np.float64(0.08000711205939975)),
 (472, np.float64(0.04836508334066745)),
 (473, np.float64(0.0)),
 (474, np.float64(0.06335829046432676)),
 (475, np.float64(0.09733285267845754)),
 (476, np.float64(0.0)),
 (477, np.float64(0.03797316245786213)),
 (478, np.float64(0.09068453126375145)),
 (479, np.float64(0.04947706959952935)),
 (480, np.float64(0.0)),
 (481, np.float64(0.02782074420373286)),
 (482, np.float64(0.11846977555181847)),
 (483, np.float64(0.03382550457458692)),
 (484, np.float64(0.05195243334661311)),
 (485, np.float64(0.05510387687779837)),
 (486, np.float64(0.12725695259515557)),
 (487, np.float64(0.07209840939145001)),
 (488, np.float64(0.0)),
 (489, np.float64(0.14159846508095775)),
 (490, np.float64(0.08240856434303293)),
 (491, np.float64(0.057353933467640436)),
 (492, np.float64(0.017914359097500464)),
 (493, np.float64(0.0)),
 (494, np.float64(0.19466570535691505)),
 (495, np.float64(0.0)),
 (496, np.float64(0.0)),
 (497, np.float64(0.06488856845230502)),
 (498, np.float64(0.0)),
 (499, np.float64(0.025976216673306556)),
 (500, np.float64(0.08240856434303293)),
 (501, np.float64(0.14509525002200235)),
 (502, np.float64(0.076004188790721)),
 (503, np.float64(0.0)),
 (504, np.float64(0.1324532357065044)),
 (505, np.float64(0.0331133089266261)),
 (506, np.float64(0.24283093212859141)),
 (507, np.float64(0.106676149412533)),
 (508, np.float64(0.024182541670333724)),
 (509, np.float64(0.0989541391990587)),
 (510, np.float64(0.08740748201220976)),
 (511, np.float64(0.05484084971070818)),

In [77]:
sorted(list(enumerate(similarity[0])),reverse = True , key = lambda x:x[1])[1:6]

[(538, np.float64(0.2433321316961438)),
 (506, np.float64(0.24283093212859141)),
 (1217, np.float64(0.23939494881986934)),
 (259, np.float64(0.23693955110363693)),
 (1925, np.float64(0.233785950059759))]

In [78]:
sorted(similarity[0],reverse=True)

[np.float64(1.0000000000000002),
 np.float64(0.2433321316961438),
 np.float64(0.24283093212859141),
 np.float64(0.23939494881986934),
 np.float64(0.23693955110363693),
 np.float64(0.233785950059759),
 np.float64(0.23174488732966075),
 np.float64(0.22710998958306755),
 np.float64(0.2252817784447915),
 np.float64(0.22305445405479846),
 np.float64(0.22256595362986292),
 np.float64(0.21296183592613543),
 np.float64(0.21239769762143662),
 np.float64(0.21073180760588117),
 np.float64(0.20942695414584772),
 np.float64(0.20780973338645242),
 np.float64(0.20751433915982237),
 np.float64(0.20647416048350561),
 np.float64(0.20443988269091456),
 np.float64(0.20437977982832192),
 np.float64(0.2029530274475215),
 np.float64(0.202677836775256),
 np.float64(0.20073876713674155),
 np.float64(0.19968076595771794),
 np.float64(0.1976738731537168),
 np.float64(0.1956463952178074),
 np.float64(0.19474520942613),
 np.float64(0.19466570535691505),
 np.float64(0.19088542889273336),
 np.float64(0.18925832465255626),
 np.float64(0.18731716231633883),
 np.float64(0.18394180184548975),
 np.float64(0.18394180184548975),
 np.float64(0.18249909877210785),
 np.float64(0.1818335167131459),
 np.float64(0.18183351671314588),
 np.float64(0.1813690625275029),
 np.float64(0.1813690625275029),
 np.float64(0.1810898182317451),
 np.float64(0.18074256993863339),
 np.float64(0.17836650794011907),
 np.float64(0.1782626071286346),
 np.float64(0.1777046633277277),
 np.float64(0.1777046633277277),
 np.float64(0.1777046633277277),
 np.float64(0.17521916101261562),
 np.float64(0.17521916101261562),
 np.float64(0.17521916101261562),
 np.float64(0.17521916101261562),
 np.float64(0.17521916101261562),
 np.float64(0.17316974359835272),
 np.float64(0.17292861596651865),
 np.float64(0.17206180040292135),
 np.float64(0.16972071444106068),
 np.float64(0.16943474841747155),
 np.float64(0.1692777916923361),
 np.float64(0.1691275228729346),
 np.float64(0.16692446522239718),
 np.float64(0.16563698349810535),
 np.float64(0.16563698349810535),
 np.float64(0.16563698349810535),
 np.float64(0.16563698349810535),
 np.float64(0.16563698349810535),
 np.float64(0.16563698349810535),
 np.float64(0.16556654463313053),
 np.float64(0.16452254913212452),
 np.float64(0.16222142113076254),
 np.float64(0.16222142113076254),
 np.float64(0.16222142113076254),
 np.float64(0.16222142113076252),
 np.float64(0.16222142113076252),
 np.float64(0.16096872731710676),
 np.float64(0.15789473684210528),
 np.float64(0.15609763526361567),
 np.float64(0.15597978123755527),
 np.float64(0.15311752374093252),
 np.float64(0.15294382258037453),
 np.float64(0.15294382258037453),
 np.float64(0.15061880828219448),
 np.float64(0.15061880828219448),
 np.float64(0.15018785229652767),
 np.float64(0.14910501299480672),
 np.float64(0.14843120879858804),
 np.float64(0.14843120879858804),
 np.float64(0.14808721943977307),
 np.float64(0.14673479641335557),
 np.float64(0.14673479641335554),
 np.float64(0.14567913668701626),
 np.float64(0.14567913668701626),
 np.float64(0.14509525002200235),
 np.float64(0.14509525002200235),
 np.float64(0.14509525002200235),
 np.float64(0.14159846508095775),
 np.float64(0.14159846508095775),
 np.float64(0.1411956236812263),
 np.float64(0.14084763640246842),
 np.float64(0.1391037210186643),
 np.float64(0.13904693239779647),
 np.float64(0.13764944032233709),
 np.float64(0.13764944032233706),
 np.float64(0.13710212427677043),
 np.float64(0.13629325512727639),
 np.float64(0.13629325512727639),
 np.float64(0.13530201829834768),
 np.float64(0.13530201829834768),
 np.float64(0.13518451760896877),
 np.float64(0.13518451760896877),
 np.float64(0.13518451760896877),
 np.float64(0.13476498501489084),
 np.float64(0.13369695534647594),
 np.float64(0.13334518676566626),
 np.float64(0.1324532357065044),
 np.float64(0.1324532357065044),
 np.float64(0.1324532357065044),
 np.float64(0.1324532357065044),
 np.float64(0.1324532357065044),
 np.float64(0.13157894736842107),
 np.float64(0.13124359177794215),
 np.float64(0.13112201362143716),
 np.float64(0.130066495428618),
 np.float64(0.130066495428618),
 np.float64(0.12988108336653278),
 np.float64(0.12988108336653278),
 np.float64(0.12977713690461004),
 np.float64(0.12977713690461004),
 np.float64(0.12977713690461004),
 np.float64(0.12940792666314374),
 np.float64(0.12824729401064427),
 np.float64(0.12824729401064427),
 np.float64(0.12824729401064427),
 np.float64(0.12725695259515557),
 np.float64(0.12725695259515557),
 np.float64(0.12725695259515557),
 np.float64(0.126673647984535),
 np.float64(0.126673647984535),
 np.float64(0.126673647984535),
 np.float64(0.12565617248750865),
 np.float64(0.12565617248750865),
 np.float64(0.12565617248750863),
 np.float64(0.12515654358043973),
 np.float64(0.12515654358043973),
 np.float64(0.12515654358043973),
 np.float64(0.12515654358043973),
 np.float64(0.12515654358043973),
 np.float64(0.12487810821089254),
 np.float64(0.12487810821089254),
 np.float64(0.12487810821089254),
 np.float64(0.12369267399882337),
 np.float64(0.12369267399882337),
 np.float64(0.12369267399882337),
 np.float64(0.12369267399882336),
 np.float64(0.12262786789699316),
 np.float64(0.12262786789699316),
 np.float64(0.12262786789699316),
 np.float64(0.12262786789699316),
 np.float64(0.12262786789699316),
 np.float64(0.12262786789699316),
 np.float64(0.12227899701112964),
 np.float64(0.12166606584807191),
 np.float64(0.12091270835166862),
 np.float64(0.12091270835166862),
 np.float64(0.12091270835166862),
 np.float64(0.12072654548783007),
 np.float64(0.1204950466257556),
 np.float64(0.11959121830873498),
 np.float64(0.11959121830873498),
 np.float64(0.11959121830873498),
 np.float64(0.11846977555181847),
 np.float64(0.11846977555181847),
 np.float64(0.11846977555181847),
 np.float64(0.11831213107007527),
 np.float64(0.11831213107007527),
 np.float64(0.11803342130469505),
 np.float64(0.11803342130469505),
 np.float64(0.11803342130469505),
 np.float64(0.11803342130469505),
 np.float64(0.11707322644771176),
 np.float64(0.11707322644771176),
 np.float64(0.11707322644771176),
 np.float64(0.116543309349613),
 np.float64(0.116543309349613),
 np.float64(0.116543309349613),
 np.float64(0.11587244366483038),
 np.float64(0.1147078669352809),
 np.float64(0.11470786693528089),
 np.float64(0.11470786693528087),
 np.float64(0.11470786693528087),
 np.float64(0.11470786693528087),
 np.float64(0.11470786693528087),
 np.float64(0.11470786693528087),
 np.float64(0.11470786693528087),
 np.float64(0.11470786693528087),
 np.float64(0.11470786693528087),
 np.float64(0.1139194873735864),
 np.float64(0.11357771260606365),
 np.float64(0.11357771260606365),
 np.float64(0.11314714296070713),
 np.float64(0.11295649894498103),
 np.float64(0.11295649894498103),
 np.float64(0.1124803176664619),
 np.float64(0.1124803176664619),
 np.float64(0.11239029738980326),
 np.float64(0.11164843913471802),
 np.float64(0.11141412945539662),
 np.float64(0.11128297681493143),
 np.float64(0.11128297681493143),
 np.float64(0.11128297681493143),
 np.float64(0.11037769642208699),
 np.float64(0.11037769642208699),
 np.float64(0.10968169942141635),
 np.float64(0.10968169942141635),
 np.float64(0.10968169942141635),
 np.float64(0.10968169942141635),
 np.float64(0.10936965981495178),
 np.float64(0.10936965981495178),
 np.float64(0.10882143751650175),
 np.float64(0.10882143751650175),
 np.float64(0.10882143751650175),
 np.float64(0.10882143751650175),
 np.float64(0.10882143751650175),
 np.float64(0.10838874619051501),
 np.float64(0.108388746190515),
 np.float64(0.10814761408717502),
 np.float64(0.10814761408717502),
 np.float64(0.10814761408717502),
 np.float64(0.10814761408717502),
 np.float64(0.10743376064838502),
 np.float64(0.106676149412533),
 np.float64(0.106676149412533),
 np.float64(0.10650358071057624),
 np.float64(0.10619884881071831),
 np.float64(0.10619884881071831),
 np.float64(0.10619884881071831),
 np.float64(0.10619884881071831),
 np.float64(0.10559715077387793),
 np.float64(0.10559715077387793),
 np.float64(0.10559715077387793),
 np.float64(0.10526315789473685),
 np.float64(0.10526315789473685),
 np.float64(0.10526315789473685),
 np.float64(0.10526315789473685),
 np.float64(0.10526315789473685),
 np.float64(0.10526315789473685),
 np.float64(0.10390486669322622),
 np.float64(0.10390486669322622),
 np.float64(0.10390486669322622),
 np.float64(0.10390486669322622),
 np.float64(0.10390486669322622),
 np.float64(0.10390486669322622),
 np.float64(0.10385162309931599),
 np.float64(0.10385162309931599),
 np.float64(0.1037571695799112),
 np.float64(0.1037571695799112),
 np.float64(0.1037571695799112),
 np.float64(0.1037571695799112),
 np.float64(0.10259783520851541),
 np.float64(0.10259783520851541),
 np.float64(0.10259783520851541),
 np.float64(0.10259783520851541),
 np.float64(0.10218988991416095),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.101338918387628),
 np.float64(0.101338918387628),
 np.float64(0.101338918387628),
 np.float64(0.101338918387628),
 np.float64(0.10092946653787335),
 np.float64(0.10060545457319173),
 np.float64(0.10012523486435178),
 np.float64(0.10012523486435178),
 np.float64(0.09984038297885897),
 np.float64(0.09933992677987831),
 np.float64(0.09933992677987831),
 np.float64(0.09933992677987831),
 np.float64(0.09933992677987831),
 np.float64(0.09933992677987831),
 np.float64(0.0993399267798783),
 np.float64(0.0989541391990587),
 np.float64(0.0989541391990587),
 np.float64(0.0989541391990587),
 np.float64(0.0989541391990587),
 np.float64(0.0989541391990587),
 np.float64(0.0989541391990587),
 np.float64(0.0989541391990587),
 np.float64(0.0989541391990587),
 np.float64(0.0978231976089037),
 np.float64(0.0978231976089037),
 np.float64(0.0978231976089037),
 np.float64(0.0978231976089037),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.0967301666813349),
 np.float64(0.0967301666813349),
 np.float64(0.0967301666813349),
 np.float64(0.0967301666813349),
 np.float64(0.0967301666813349),
 np.float64(0.0967301666813349),
 np.float64(0.09673016668133488),
 np.float64(0.09567297464698798),
 np.float64(0.09567297464698798),
 np.float64(0.09567297464698798),
 np.float64(0.09558988911273408),
 np.float64(0.09544271444636668),
 np.float64(0.09544271444636668),
 np.float64(0.09544271444636668),
 np.float64(0.09544271444636668),
 np.float64(0.09544271444636668),
 np.float64(0.09544271444636668),
 np.float64(0.09544271444636668),
 np.float64(0.09544271444636668),
 np.float64(0.09544271444636668),
 np.float64(0.09464970485606021),
 np.float64(0.09464970485606021),
 np.float64(0.09464970485606021),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09269795493186431),
 np.float64(0.09269795493186431),
 np.float64(0.09269795493186431),
 np.float64(0.09197090092274487),
 np.float64(0.09197090092274487),
 np.float64(0.09197090092274487),
 np.float64(0.09197090092274487),
 np.float64(0.09197090092274487),
 np.float64(0.09197090092274487),
 np.float64(0.09197090092274487),
 np.float64(0.09197090092274487),
 np.float64(0.09197090092274487),
 np.float64(0.09183979479633063),
 np.float64(0.09183979479633063),
 np.float64(0.09176629354822471),
 np.float64(0.09086217008485092),
 np.float64(0.09068453126375145),
 np.float64(0.09068453126375145),
 np.float64(0.09037128496931669),
 np.float64(0.09037128496931669),
 np.float64(0.09037128496931669),
 np.float64(0.09037128496931669),
 np.float64(0.09037128496931669),
 np.float64(0.08998425413316952),
 np.float64(0.08998425413316952),
 np.float64(0.08998425413316952),
 np.float64(0.08998425413316952),
 np.float64(0.08998425413316952),
 np.float64(0.08998425413316952),
 np.float64(0.0891313035643173),
 np.float64(0.0891313035643173),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08849904067559859),
 np.float64(0.08830215713766959),
 np.float64(0.08830215713766959),
 np.float64(0.08830215713766959),
 np.float64(0.08830215713766959),
 np.float64(0.08797691788472337),
 np.float64(0.08749572785196143),
 np.float64(0.08749572785196143),
 np.float64(0.08749572785196143),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08671099695241201),
 np.float64(0.08671099695241201),
 np.float64(0.08671099695241201),
 np.float64(0.08671099695241201),
 np.float64(0.08671099695241201),
 np.float64(0.08671099695241201),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08594700851870801),
 np.float64(0.08594700851870801),
 np.float64(0.08594700851870801),
 np.float64(0.08594700851870801),
 np.float64(0.08520286456846099),
 np.float64(0.08520286456846099),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.0845637614364673),
 np.float64(0.08447772061910234),
 np.float64(0.0837707816583391),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.0830812984794528),
 np.float64(0.08240856434303293),
 np.float64(0.08240856434303293),
 np.float64(0.08240856434303293),
 np.float64(0.08240856434303291),
 np.float64(0.08226127456606226),
 np.float64(0.08226127456606226),
 np.float64(0.08226127456606226),
 np.float64(0.08226127456606226),
 np.float64(0.08226127456606226),
 np.float64(0.08226127456606226),
 np.float64(0.08226127456606226),
 np.float64(0.08226127456606226),
 np.float64(0.08226127456606226),
 np.float64(0.08175191193132876),
 np.float64(0.08175191193132876),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08048436365855338),
 np.float64(0.08048436365855338),
 np.float64(0.08048436365855338),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.0792740035289418),
 np.float64(0.0792740035289418),
 np.float64(0.07894736842105264),
 np.float64(0.07894736842105264),
 np.float64(0.07894736842105264),
 np.float64(0.07894736842105264),
 np.float64(0.07894736842105264),
 np.float64(0.07894736842105264),
 np.float64(0.07894736842105264),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.0781166566864507),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07755667343294813),
 np.float64(0.07755667343294813),
 np.float64(0.07755667343294813),
 np.float64(0.07698687947429833),
 np.float64(0.07694837640638656),
 np.float64(0.07694837640638656),
 np.float64(0.07694837640638656),
 np.float64(0.07694837640638656),
 np.float64(0.07694837640638656),
 np.float64(0.07694837640638656),
 np.float64(0.07694837640638656),
 np.float64(0.07694837640638656),
 np.float64(0.07664241743562072),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),
 np.float64(0.07630253807827608),
 np.float64(0.076004188790721),
 np.float64(0.076004188790721),
 np.float64(0.076004188790721),
 np.float64(0.076004188790721),
 np.float64(0.07594632491572426),
 np.float64(0.07509392614826384),
 np.float64(0.07509392614826384),
 np.float64(0.07509392614826384),
 np.float64(0.07509392614826384),
 np.float64(0.07509392614826384),
 np.float64(0.07509392614826384),
 np.float64(0.07509392614826384),
 np.float64(0.07509392614826384),
 np.float64(0.07509392614826384),
 np.float64(0.07492686492653551),
 np.float64(0.07443229275647868),
 np.float64(0.07443229275647868),
 np.float64(0.07443229275647868),
 np.float64(0.07443229275647868),
 np.float64(0.07443229275647868),
 np.float64(0.07443229275647868),
 np.float64(0.07443229275647868),
 np.float64(0.07443229275647868),

In [79]:
def recommend(movie):
  movie_index = new_df[new_df['title'] == movie].index[0]
  distances = similarity[movie_index]
  movies_list = sorted(list(enumerate(distances)),reverse = True , key = lambda x:x[1])[1:6]

  for i in movies_list:
    print(new_df.iloc[i[0]].title)

In [80]:
new_df[new_df['title'] == 'Batman Begins'].index[0]

np.int64(119)

In [81]:
recommend('Avatar')

Titan A.E.
Independence Day
Aliens vs Predator: Requiem
Ender's Game
Lifeforce

In [82]:
new_df.iloc[1217].title

'Aliens vs Predator: Requiem'

In [83]:
import pickle

In [84]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [86]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], shape=(4838,), dtype=object)

In [87]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

In [88]:
pickle.dump(similarity,open('similarity.pkl','wb'))